### ISSUE TITLE
Leaderboard issue (again)

### ISSUE THREAD

**Issue by TheSikon** [MinersHavenPlus/Miners-Haven-Plus#27]
So i was rebirthing alot lately hopefully getting into leaderboard but ive passed the 3 last people on it (highest life) but it didnt show it even after a while or waiting and rejoining server.
The main problem is leaderboard getting stuck and not refreshing properly. and thanks for your time
sincerly, focus-diyaadiyaa

**Comment by bryce-happel-walton** [comment]
This is not a bug. The problem is that the datastores can only be accessed and updated so many times in a period of time. If the server you are in takes up datastore requests at the time your data would be uploaded to the datastore then it will be added to a queue, and if you leave while in queue then it won't update at all.
